Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2021-09, with the labels that each got.

#142 Update CI configration to supprot galactic and rolling
  .github/workflows/ci-build-binary-galactic.yml
  .github/workflows/ci-build-binary-rolling.yml
  .github/workflows/ci-build-binary.yml
  .github/workflows/ci-build-coverage.yml
  .github/workflows/ci-build-semi-binary.yml
  .github/workflows/ci-build-source.yml
  .github/workflows/ci-format.yml
  .github/workflows/ci-ros-lint.yml
  .github/workflows/ci-ursim.yml
  README.md
  Universal_Robots_ROS2_Driver-not-released.foxy.repos
  Universal_Robots_ROS2_Driver-not-released.galactic.repos
  Universal_Robots_ROS2_Driver-not-released.rolling.repos
  ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
  ur_controllers/src/scaled_joint_trajectory_controller.cpp
  ur_robot_driver/src/hardware_interface.cpp
Labels: enhancement, future-work

#176 [foxy] Fix ci status badges
  README.md
Labels: documentation

#175 [main] Fix ci status badges
  README.md
Labels: documentation

#184 README readability improvements
  README.md
Labels: documentation

#191 Fix prepare and perform switch operation
  ur_robot_driver/src/hardware_interface.cpp
Labels: bug
