Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2022-06, with the labels that each got.

#345 Fix coverage build
  .github/workflows/coverage-build.yml
  .github/workflows/rolling-source-build.yml
Labels: humble+

#373 Foxy: Update dependencies and binary repos file
  .github/workflows/foxy-binary-build.yml
  README.md
  Universal_Robots_ROS2_Driver-not-released.foxy.repos
  ur_bringup/launch/test_joint_trajectory_controller.launch.py
  ur_bringup/launch/test_scaled_joint_trajectory_controller.launch.py
  ur_bringup/package.xml
Labels: Foxy

#377 Update HW-interface API for humble.
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/hardware_interface.cpp
  ur_robot_driver/src/ur_ros2_control_node.cpp
Labels: humble+

#386 Remove source builds
  .github/workflows/foxy-source-build.yml
  .github/workflows/galactic-source-build.yml
  README.md
Labels: CI

#392 Fix dependencies for galactic
  ur_bringup/package.xml
  ur_controllers/CMakeLists.txt
  ur_controllers/package.xml
  ur_moveit_config/package.xml
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/package.xml
Labels: galactic

#385 Add galactic source build on galactic branch
  .github/workflows/galactic-source-build.yml
Labels: galactic, CI

#393 Force galactic branch for scheduled builds
  .github/workflows/galactic-binary-build.yml
  .github/workflows/galactic-semi-binary-build.yml
Labels: galactic, CI

#396 Remove Foxy upstream not-released file
  .github/workflows/foxy-binary-build.yml
Labels: Foxy, CI

#406 Fix force_torque_sensor_broadcaster config
  ur_bringup/config/ur_controllers.yaml
Labels: galactic

#402 Update README badges
  README.md
Labels: backport-galactic, backport-foxy

#423 Remove vcstool instruction for galactic
  README.md
Labels: documentation, galactic
