Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2022-05, with the labels that each got.

#285 Update header extension to remove compile warning.
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
Labels: humble+

#339 Use types in hardware interface from ros2_control in local namespace
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/hardware_interface.cpp
Labels: humble+

#351 Update controllers' API
  ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
  ur_controllers/include/ur_controllers/speed_scaling_state_broadcaster.hpp
  ur_controllers/src/gpio_controller.cpp
  ur_controllers/src/scaled_joint_trajectory_controller.cpp
  ur_controllers/src/speed_scaling_state_broadcaster.cpp
Labels: humble+

#364 Fix repos file for scheduled foxy source build
  .github/workflows/foxy-source-build.yml
Labels: Foxy, CI

#369 Readme binary installation
  .github/workflows/galactic-binary-build.yml
  README.md
  Universal_Robots_ROS2_Driver-not-released.galactic.repos
  Universal_Robots_ROS2_Driver-not-released.rolling.repos
  Universal_Robots_ROS2_Driver.galactic.repos
  Universal_Robots_ROS2_Driver.rolling.repos
Labels: galactic

#324 Foxy controller stopper
  ur_bringup/launch/ur_control.launch.py
  ur_controllers/include/ur_controllers/gpio_controller.hpp
  ur_controllers/src/gpio_controller.cpp
  ur_description/urdf/ur.ros2_control.xacro
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/README.md
  ur_robot_driver/include/ur_robot_driver/controller_stopper.hpp
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/controller_stopper.cpp
  ur_robot_driver/src/controller_stopper_node.cpp
  ur_robot_driver/src/hardware_interface.cpp
Labels: Foxy

#371 Correct foxy source build repos file
  .github/workflows/foxy-source-build.yml
Labels: Foxy, CI
