Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2024-06, with the labels that each got.

#990 Add servo node config to disable advertising /get_planning_scene
  ur_moveit_config/config/ur_servo.yaml
Labels: backport-humble, iron

#1017 Fix calibration
  .pre-commit-config.yaml
  ur_calibration/doc/algorithm.rst
  ur_calibration/doc/calibration_example.png
  ur_calibration/doc/calibration_example_corrected.png
  ur_calibration/doc/calibration_uncorrected.png
  ur_calibration/doc/conf.py
  ur_calibration/doc/index.rst
  ur_calibration/doc/usage.rst
  ur_calibration/src/calibration.cpp
  ur_calibration/test/calibration_test.cpp
Labels: backport-humble, backport-iron

#1019 Remove real_time installation guide from docs
  ur_robot_driver/doc/installation/installation.rst
  ur_robot_driver/doc/installation/real_time.rst
  ur_robot_driver/doc/installation/toc.rst
Labels: documentation

#1026 Prerelease/2.2.13
  ur/CHANGELOG.rst
  ur/package.xml
  ur_bringup/CHANGELOG.rst
  ur_bringup/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: humble

#1024 Prerelease/2.3.8
  ur/CHANGELOG.rst
  ur/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: iron
