Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2024-12, with the labels that each got.

#1197 Initialize segments in constructor of DHRobot in calibration.hpp
  ur_calibration/include/ur_calibration/calibration.hpp
Labels: backport-humble

#1203 Update package maintainers
  ur/package.xml
  ur_calibration/package.xml
  ur_controllers/package.xml
  ur_dashboard_msgs/package.xml
  ur_moveit_config/package.xml
  ur_robot_driver/package.xml
Labels: backport-humble

#1209 Add control_toolbox to semi-binary repos file
  Universal_Robots_ROS2_Driver.humble.repos
Labels: humble

#1213 Release/2.5.0
  ur/CHANGELOG.rst
  ur/package.xml
  ur_bringup/CHANGELOG.rst
  ur_bringup/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: humble

#1212 Release/3.0.0
  ur/CHANGELOG.rst
  ur/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: rolling, Jazzy

#1215 Add missing test dependencies for ur_controllers
  ur_controllers/package.xml
Labels: backport-humble

#1220 Remove unused visibility macros include
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
Labels: backport-humble
