Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2024-10, with the labels that each got.

#1107 Assure the description is loaded as string
  ur_robot_driver/launch/ur_control.launch.py
Labels: backport-humble

#964 Service to get software version of robot
  ur_controllers/CMakeLists.txt
  ur_controllers/controller_plugins.xml
  ur_controllers/include/ur_controllers/ur_configuration_controller.hpp
  ur_controllers/src/ur_configuration_controller.cpp
  ur_controllers/src/ur_configuration_controller_parameters.yaml
  ur_robot_driver/config/ur_controllers.yaml
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/launch/ur_control.launch.py
  ur_robot_driver/src/hardware_interface.cpp
  ur_robot_driver/test/robot_driver.py
  ur_robot_driver/test/test_common.py
Labels: backport-humble, backport-iron

#1125 Update ur_msgs upstream branch
  Universal_Robots_ROS2_Driver.iron.repos
Labels: CI, iron

#1126 Update ur_msgs upstream branch
  Universal_Robots_ROS2_Driver.humble.repos
Labels: humble, CI

#1124 Update ur_msgs branch for upstream workspaces
  Universal_Robots_ROS2_Driver-not-released.humble.repos
  Universal_Robots_ROS2_Driver-not-released.iron.repos
  Universal_Robots_ROS2_Driver.galactic.repos
  Universal_Robots_ROS2_Driver.humble.repos
  Universal_Robots_ROS2_Driver.iron.repos
  Universal_Robots_ROS2_Driver.jazzy.repos
  Universal_Robots_ROS2_Driver.rolling.repos
Labels: CI

#1123 Allow setting the analog output domain when setting an analog output
  ur_controllers/doc/index.rst
  ur_controllers/include/ur_controllers/gpio_controller.hpp
  ur_controllers/src/gpio_controller.cpp
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/hardware_interface.cpp
  ur_robot_driver/urdf/ur.ros2_control.xacro
Labels: backport-humble, backport-iron

#1134 [moveit] Disable execution_duration_monitoring by default
  ur_moveit_config/launch/ur_moveit.launch.py
Labels: iron

#1133 [moveit] Disable execution_duration_monitoring by default
  ur_moveit_config/launch/ur_moveit.launch.py
  ur_robot_driver/doc/usage.rst
Labels: humble

#1137 Readme update hosted docs
  .github/helpers/check_urls.sh
  .github/workflows/check_links.yml
  README.md
Labels: documentation

#1122 Adjust alignment and size of family photo
  README.md
Labels: backport-humble, backport-iron

#1146 [moveit] Properly handle use_sim_time
  ur_moveit_config/launch/ur_moveit.launch.py
Labels: backport-humble, iron
