Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2024-11, with the labels that each got.

#1176 Update Humble upstream workspace
  Universal_Robots_ROS2_Driver-not-released.humble.repos
  Universal_Robots_ROS2_Driver.humble.repos
Labels: humble

#1177 Cleanup workflows
  .github/workflows/humble-binary-main.yml
  .github/workflows/humble-binary-testing.yml
  .github/workflows/humble-semi-binary-main.yml
  .github/workflows/humble-semi-binary-testing.yml
  .github/workflows/iron-binary-main.yml
  .github/workflows/iron-binary-testing.yml
  .github/workflows/iron-semi-binary-main.yml
  .github/workflows/iron-semi-binary-testing.yml
  .github/workflows/jazzy-binary-main.yml
  .github/workflows/jazzy-binary-testing.yml
  .github/workflows/jazzy-semi-binary-main.yml
  .github/workflows/jazzy-semi-binary-testing.yml
  .github/workflows/reusable_ici.yml
  .github/workflows/rolling-binary-main.yml
  .github/workflows/rolling-binary-testing.yml
  .github/workflows/rolling-semi-binary-main.yml
  .github/workflows/rolling-semi-binary-testing.yml
  Universal_Robots_ROS2_Driver.jazzy.repos
  Universal_Robots_ROS2_Driver.rolling.repos
Labels: CI

#1108 Use pose_broadcaster to publish the TCP pose
  ur_robot_driver/config/ur_controllers.yaml
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/launch/ur_control.launch.py
  ur_robot_driver/package.xml
  ur_robot_driver/src/hardware_interface.cpp
Labels: backport-humble, backport-iron

#944 Forward trajectory controller
  ur_controllers/CMakeLists.txt
  ur_controllers/controller_plugins.xml
  ur_controllers/doc/index.rst
  ur_controllers/include/ur_controllers/passthrough_trajectory_controller.hpp
  ur_controllers/package.xml
  ur_controllers/src/passthrough_trajectory_controller.cpp
  ur_controllers/src/passthrough_trajectory_controller_parameters.yaml
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/config/ur_controllers.yaml
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/launch/ur10.launch.py
  ur_robot_driver/launch/ur10e.launch.py
  ur_robot_driver/launch/ur16e.launch.py
  ur_robot_driver/launch/ur20.launch.py
  ur_robot_driver/launch/ur3.launch.py
  ur_robot_driver/launch/ur30.launch.py
  ur_robot_driver/launch/ur3e.launch.py
  ur_robot_driver/launch/ur5.launch.py
  ur_robot_driver/launch/ur5e.launch.py
  ur_robot_driver/launch/ur_control.launch.py
  ur_robot_driver/scripts/example_move.py
  ur_robot_driver/src/hardware_interface.cpp
  ur_robot_driver/test/integration_test_controller_switch.py
  ur_robot_driver/test/robot_driver.py
  ur_robot_driver/test/test_common.py
  ur_robot_driver/urdf/ur.ros2_control.xacro
Labels: backport-humble, backport-iron

#1049 Add force mode controller
  ur_controllers/CMakeLists.txt
  ur_controllers/controller_plugins.xml
  ur_controllers/doc/index.rst
  ur_controllers/include/ur_controllers/force_mode_controller.hpp
  ur_controllers/package.xml
  ur_controllers/src/force_mode_controller.cpp
  ur_controllers/src/force_mode_controller_parameters.yaml
  ur_controllers/test/force_mode_controller_params.yaml
  ur_controllers/test/test_load_force_mode_controller.cpp
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/config/ur_controllers.yaml
  ur_robot_driver/doc/usage/controllers.rst
  ur_robot_driver/examples/examples.py
  ur_robot_driver/examples/force_mode.py
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/launch/ur_control.launch.py
  ur_robot_driver/src/hardware_interface.cpp
  ur_robot_driver/test/integration_test_controller_switch.py
  ur_robot_driver/test/integration_test_force_mode.py
  ur_robot_driver/test/robot_driver.py
  ur_robot_driver/test/test_common.py
  ur_robot_driver/urdf/ur.ros2_control.xacro
Labels: backport-humble
