Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2024-05, with the labels that each got.

#985 Remove dependency to docker.io
  .github/workflows/reusable_ici.yml
  ur_robot_driver/package.xml
Labels: backport-humble, backport-iron

#978 [GPIO Controller] Use latched publishing for robot_mode and safety_mode
  ur_controllers/src/gpio_controller.cpp
Labels: backport-humble, backport-iron

#984 General docs
  ur_calibration/README.md
  ur_calibration/doc/index.rst
  ur_controllers/README.md
  ur_controllers/doc/index.rst
  ur_moveit_config/doc/index.rst
  ur_robot_driver/README.md
  ur_robot_driver/doc/ROS_INTERFACE.md
  ur_robot_driver/doc/ROS_INTERFACE.rst
  ur_robot_driver/doc/index.rst
  ur_robot_driver/doc/installation/real_time.md
  ur_robot_driver/doc/installation/real_time.rst
  ur_robot_driver/doc/usage.rst
Labels: documentation

#882 Attempt to fix the goal time violated issue
  ur_controllers/src/scaled_joint_trajectory_controller.cpp
Labels: backport-humble, backport-iron

#1003 Use robot_receive_timeout instead of keepalive_count
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/hardware_interface.cpp
Labels: backport-humble, iron

#1010 Remove extra spaces from start_ursim statement in tests
  ur_robot_driver/test/test_common.py
Labels: backport-humble, backport-iron
