Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2025-09, with the labels that each got.

#1486 Update ros2_bug.yaml
  .github/ISSUE_TEMPLATE/ros2_bug.yaml
Labels: package

#1474 Realtime tools migration
  ur_controllers/include/ur_controllers/force_mode_controller.hpp
  ur_controllers/include/ur_controllers/passthrough_trajectory_controller.hpp
  ur_controllers/include/ur_controllers/tool_contact_controller.hpp
  ur_controllers/include/ur_controllers/ur_configuration_controller.hpp
  ur_controllers/src/force_mode_controller.cpp
  ur_controllers/src/passthrough_trajectory_controller.cpp
  ur_controllers/src/tool_contact_controller.cpp
  ur_controllers/src/ur_configuration_controller.cpp
Labels: backport-jazzy, bugfix

#1502 Release/4.2.0
  ur/CHANGELOG.rst
  ur/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: release

#1503 Release/2.9.0
  ur/CHANGELOG.rst
  ur/package.xml
  ur_bringup/CHANGELOG.rst
  ur_bringup/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: release

#1504 Release/3.4.0
  ur/CHANGELOG.rst
  ur/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: release

#1226 Running integration tests with mock hardware
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/test/integration_test_config_controller.py
  ur_robot_driver/test/integration_test_controller_switch.py
  ur_robot_driver/test/integration_test_force_mode.py
  ur_robot_driver/test/integration_test_io_controller.py
  ur_robot_driver/test/integration_test_passthrough_controller.py
  ur_robot_driver/test/integration_test_scaled_joint_controller.py
  ur_robot_driver/test/integration_test_tool_contact.py
  ur_robot_driver/test/robot_driver.py
  ur_robot_driver/test/test_common.py
  ur_robot_driver/test/test_mock_hardware.py
  ur_robot_driver/urdf/ur.ros2_control.xacro
Labels: CI, backport-humble, backport-jazzy
