Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2025-03, with the labels that each got.

#933 Port robot_state_helper to ROS2
  ur_dashboard_msgs/action/SetMode.action
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/doc/controller_stopper.rst
  ur_robot_driver/doc/index.rst
  ur_robot_driver/doc/robot_state_helper.rst
  ur_robot_driver/doc/usage/startup.rst
  ur_robot_driver/include/ur_robot_driver/robot_state_helper.hpp
  ur_robot_driver/launch/ur_control.launch.py
  ur_robot_driver/src/robot_state_helper.cpp
  ur_robot_driver/src/robot_state_helper_node.cpp
Labels: backport-humble

#1287 Update transformForceTorque to handle wheter it is a cb3 or an e-Series robot
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/resources/rtde_output_recipe.txt
  ur_robot_driver/src/hardware_interface.cpp
Labels: requires testing, backport-humble

#1303 Fix links to forward command controllers
  ur_robot_driver/doc/usage/controllers.rst
Labels: documentation

#1314 Fix passthrough controller to not read non-existing state_interfaces
  ur_controllers/src/passthrough_trajectory_controller.cpp
  ur_robot_driver/test/robot_driver.py
Labels: backport-humble

#1321 Remove semi-binary testing builds from ci_status
  ci_status.md
Labels: backport-humble
