Repository UniversalRobots/Universal_Robots_ROS2_Driver, pull requests merged in 2025-06, with the labels that each got.

#1385 Use std_atomic<bool> in SJTC
  ur_controllers/src/scaled_joint_trajectory_controller.cpp
Labels: backport-humble, backport-jazzy, bugfix

#1389 Remove unneccessary arguments.
  ur_robot_driver/launch/ur_rsp.launch.py
Labels: backport-jazzy

#1392 Ignore deprecation warning for set_gains for now
  ur_controllers/src/scaled_joint_trajectory_controller.cpp
Labels: package, backport-jazzy

#1391 Use the Python mirror for clang-format in pre-commit config
  .pre-commit-config.yaml
Labels: CI, backport-humble, backport-jazzy

#1395 Release/2.8.1
  ur/CHANGELOG.rst
  ur/package.xml
  ur_bringup/CHANGELOG.rst
  ur_bringup/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: release

#1401 Release/4.0.2
  ur/CHANGELOG.rst
  ur/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: release

#1394 Fix semi-binary builds for Kilted & Rolling
  Universal_Robots_ROS2_Driver.kilted.repos
  Universal_Robots_ROS2_Driver.rolling.repos
Labels: CI

#1410 Use new API of PID class
  ur_controllers/src/scaled_joint_trajectory_controller.cpp
Labels: backport-jazzy

#1417 Refactor prepare_switch method
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/hardware_interface.cpp
Labels: backport-humble, backport-jazzy

#1421 ur_robot_driver: Fix compilation on Windows
  ur_robot_driver/CMakeLists.txt
  ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
  ur_robot_driver/src/hardware_interface.cpp
  ur_robot_driver/src/robot_state_helper.cpp
Labels: backport-humble, backport-jazzy

#1430 Release/3.3.3
  ur/CHANGELOG.rst
  ur/package.xml
  ur_calibration/CHANGELOG.rst
  ur_calibration/package.xml
  ur_controllers/CHANGELOG.rst
  ur_controllers/package.xml
  ur_dashboard_msgs/CHANGELOG.rst
  ur_dashboard_msgs/package.xml
  ur_moveit_config/CHANGELOG.rst
  ur_moveit_config/package.xml
  ur_robot_driver/CHANGELOG.rst
  ur_robot_driver/package.xml
Labels: Jazzy, release
